# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 422654cbbc9d9f5aecd238591df3013cbf0137d3c1d6fcb21624771c7618dadb1d4680914c87a19e631d5d7021dd25c5e79b8f85caa9fbe88fd68a545aa5d9e3

test:
  secret_key_base: 4dd4024122e796a532ce4f9c97a128716ea12d41e67e6b15541aaec96df9a6569bc509198881e94360ae5d7a8b7e20535f434de8bdc9f831a9f455247943c862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
